config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :mml_patients
  resources :compositions
  resources :mml_lab_tests
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :contact
  has_many :address_details
end

app/models/category.rb
class Category < CodeSet

end

app/models/cluster.rb
class Cluster < Item
  has_many :item_proxies
  has_many :items, through: :item_proxies
end

app/models/code_group.rb
class CodeGroup < ActiveRecord::Base
end

app/models/code_set.rb
class CodeSet < ActiveRecord::Base
  belongs_to :language, polymorphic: true
end

app/models/component.rb
class Component < ApplicationRecord
  belongs_to :version_lifecycle_status
  belongs_to :language
  belongs_to :ehr
  belongs_to :party_proxy
end

app/models/composition.rb
class Composition < Component
  has_many :content_items
  belongs_to :category

  def partial
    "#{name.downcase.tr(' ', '_')}"
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :party, polymorphic: true
  has_many :addresses
end

app/models/content.rb
class Content < ActiveRecord::Base
  belongs_to :content
end

app/models/data_value.rb
class DataValue < ActiveRecord::Base
  belongs_to :item, polymorphic: true
end

app/models/dv_date.rb
class DvDate < DataValue
  alias_attribute :value, :date_value

  validates :date_value, presence: true
end

app/models/dv_text.rb
class DvText < DataValue
  alias_attribute :value, :text_value
end

app/models/ehr.rb
class Ehr < ActiveRecord::Base
  belongs_to :person
  has_many :compositions
end

app/models/element.rb
class Element < Item
  belongs_to :item_proxy
end

app/models/entry.rb
class Entry < ContentItem
end

app/models/folder.rb
class Folder < Component
  has_many :component_proxies
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :content_item, polymorphic: true
  belongs_to :item_proxy
end

app/models/language.rb
class Language < ActiveRecord::Base
end

app/models/party.rb
class Party < ActiveRecord::Base
  has_many :party_identities
  has_many :contacts
  has_many :addresses, through: :contacts
  has_many :party_details
end

app/models/person.rb
class Person < Party
  has_one :ehr

  def master_id
    party_identities.find_by(name: 'regional id').
      identity_details.
      find_by(name: 'maiko id').value
  end

  def person_name
    @person_name ||= party_identities.build(name: 'person name', purpose: 'legal name')
  end

  def first_name
    party_identities.find_by(name: 'person name').identity_details.find_by(name: 'given name').value
  end

  def family_name
    party_identities.find_by(name: 'person name').identity_details.find_by(name: 'family name').value
  end

  def given_name
    party_identities.
      find_by(name: 'person name', purpose: 'legal name').
      identity_details.
      find_by(name: 'given name')
  end

  def birthday
    bd = party_details.
      find_by(name: 'general').
      detail_items.find_by(name: 'birthday').value
    Date.parse(bd)
  end

  def sex
    party_details.find_by(name: 'general').
      detail_items.find_by(name: 'gender').value
  end
end

app/models/section.rb
class Section < ContentItem
  has_many :content_items
end

app/controllers/compositions_controller.rb
class CompositionsController < ApplicationController
  before_action :set_composition, only: [:show] 

  def index
    @compositions = Composition.all
  end

  def show
    @title = 'Test result'
    respond_to do |format|
      format.html
      format.json
      format.xml
    end
  end

  private
    def set_composition
      @composition = Composition.find(params[:id])
    end

    def composition_params
      params.require(:composition).permit(:id)
    end
end

app/helpers/compositions_helper.rb
module CompositionsHelper
end

app/views/compositions/_mml_lab_test.html.erb
<table class="table table-striped table-bordered">
 <thead>
  <tr>
    <th>項目名称</th>
    <th>数値</th>
    <th>単位</th>
  </tr>
 </thead>
  <% @composition.content_items.each do |content_item| %>
  <tr>
    <td><%= content_item.items.find_by(nodeid: 'at0005').data_value.text_value %></td>
    <td><%= content_item.items.find_by(nodeid: 'at0078').data_value.decimal_value %></td>
    <td><%= content_item.items.find_by(nodeid: 'at0078').data_value.unit %></td>
  </tr>
  <% end %>
</table>

app/views/compositions/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <b>ID:</b> <%= @composition.ehr.person.master_id %>
    </div>
    <div class="col-md-4">
      <b>氏名:</b> <%= @composition.ehr.person.family_name %><%= @composition.ehr.person.first_name %>
    </div>
    <div class="col-md-3">
      <b>生年月日:</b> <%= @composition.ehr.person.birthday %>
    </div>
    <div class="2">
      <b>性別:</b> <%= @composition.ehr.person.sex %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <b>文書種別:</b> <%= @composition.name %>
    </div>
    <div class="col-md-3">
      <b>登録ID:</b> <%= @composition.uid %>      
    </div>
    <div class="col-md-6">
      <b>登録日時:</b> <%= @composition.created_at %>            
    </div>
  </div>
</div>
<%=  render "#{@composition.partial}" %>
<%= link_to 'MML', composition_path(format: :xml) %> |<%= link_to '戻る', mml_patients_path %>