config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :mml_patients
  resources :compositions
  resources :mml_lab_tests
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :contact
  has_many :address_details
end

app/models/category.rb
class Category < CodeSet

end

app/models/cluster.rb
class Cluster < Item
  has_many :item_proxies
  has_many :items, through: :item_proxies
end

app/models/code_group.rb
class CodeGroup < ActiveRecord::Base
end

app/models/code_set.rb
class CodeSet < ActiveRecord::Base
  belongs_to :language, polymorphic: true
end

app/models/component.rb
class Component < ApplicationRecord
  belongs_to :version_lifecycle_status
  belongs_to :language
  belongs_to :ehr
  belongs_to :party_proxy
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :party, polymorphic: true
  has_many :addresses
end

app/models/content.rb
class Content < ActiveRecord::Base
  belongs_to :content
end

app/models/data_value.rb
class DataValue < ActiveRecord::Base
  belongs_to :item, polymorphic: true
end

app/models/dv_date.rb
class DvDate < DataValue
  alias_attribute :value, :date_value

  validates :date_value, presence: true
end

app/models/dv_text.rb
class DvText < DataValue
  alias_attribute :value, :text_value
end

app/models/ehr.rb
class Ehr < ActiveRecord::Base
  belongs_to :person
  has_many :compositions
end

app/models/element.rb
class Element < Item
  belongs_to :item_proxy
end

app/models/entry.rb
class Entry < ContentItem
end

app/models/folder.rb
class Folder < Component
  has_many :component_proxies
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :content_item, polymorphic: true
  belongs_to :item_proxy
end

app/models/language.rb
class Language < ActiveRecord::Base
end

app/models/mml_patient.rb
require 'mml'

class MMLPatient < Person
  after_save do
    party_identities.each do |identity|
      identity.save
      identity.identity_details do |detail|
        detail.save
        detail.detail_items do |item|
          item.save
        end
      end
    end
    party_details.each do |detail|
      detail.save
    end
  end

  def master_id
    MML::Id.new(value: super)
  end

  def master_id=(master_id)
    party_identities.build(name: 'regional id').identity_details.build(name: 'maiko id', value: master_id.value)
  end

  def other_ids
    party_identities.where(name: 'local id').map do |id|
      {issuer: id.purpose, id: id.identity_details.find_by(name: 'id').value}
    end
  end

  def other_ids=(ids)
    ids.each do |id|
      id.each do |k, v|
        party_identities.build(name: 'local id', purpose: k).identity_details.build(name: 'id', value: v)
      end
    end
  end

  def first_name=(first_name)
    person_name.identity_details.build(name: 'given name', value: first_name)
  end

  def family_name=(family_name)
    person_name.identity_details.build(name: 'family name', value: family_name)
  end

  def given_name=(given_name)
    person_name.identity_details.
      build(name: 'given name', value: given_name)
  end

  def name
    party_identities.where(name: 'person name').map do |identity|
      family_name = family_name(identity)
      given_name = given_name('given name')
      full_name = find_name_by_type('full name')
      MML::Name.new(family_name: family_name, given_name: given_name, full_name: full_name)
    end
  end

  def details_general
    @details_general ||= party_details.build(name: 'general')
  end

  # def birthday
  #   Date.parse details_general.detail_items.find_by(name: 'birthday').value
  # end

  def birthday=(birthday)
    bd = Date.parse(birthday)
    details_general.detail_items.build(name: 'birthday', value: bd)
  end

  # def sex
  #   details_general.detail_items.find_by('gender').value
  # end

  def sex=(sex)
    details_general.detail_items.build(name: 'gender', value: sex)
  end

  def nationality
    party_details.find_by(name: 'general').
      detail_items.find_by(name: 'nationality').value
  end

  def nationality=(nationality)
    details_general.detail_items.
      build(name: 'nationality', value: nationality)
  end

  def marital
    party_details.find_by(name: 'general').
      detail_items.find_by(name: 'marital').value
  end

  def marital=(marital)
    details_general.detail_items.
      build(name: 'marital', value: marital)
  end

  def postal_addresses
    addresses.where(meaning: 'postal address')
  end

  def postal_addresses=(addresses)
    addresses.each do |name, details|
      contacts.build(name: name).addresses.
        build(meaning: 'postal address', name: name).
        address_details.build(details.map {|k,v| {name: k, value: v}})
    end
  end

  def phones
    addresses.where(name: 'phone')
  end

#  scope :phones, -> {self.addresses.where(name: 'phone')}

  def phones=(phones)
    phones.each do |name, details|
      contacts.build(name: name).addresses.
        build(meaning: 'telecom address', name: 'phone').
        address_details.build(details.map {|k,v| {name: k, value: v} })
    end
  end

  def family_name(identity)
    find_name_by_type(identity, 'family name')
  end

  def find_name_by_type(identity, type)
    confirm_name_by_type(type).exist? ? confirm_name_by_type(type).value : nil
  end

  def confirm_namename_by_type(type)
    identity.identity_details.find_by(name: type).exist?
  end

  def to_mml
    MML::Patient.info.new(masterId: masterId, birthday: birthday, sex: sex, nationality: nationality, marital: marital)
  end
end

app/models/party.rb
class Party < ActiveRecord::Base
  has_many :party_identities
  has_many :contacts
  has_many :addresses, through: :contacts
  has_many :party_details
end

app/models/person.rb
class Person < Party
  has_one :ehr

  def master_id
    party_identities.find_by(name: 'regional id').
      identity_details.
      find_by(name: 'maiko id').value
  end

  def person_name
    @person_name ||= party_identities.build(name: 'person name', purpose: 'legal name')
  end

  def first_name
    party_identities.find_by(name: 'person name').identity_details.find_by(name: 'given name').value
  end

  def family_name
    party_identities.find_by(name: 'person name').identity_details.find_by(name: 'family name').value
  end

  def given_name
    party_identities.
      find_by(name: 'person name', purpose: 'legal name').
      identity_details.
      find_by(name: 'given name')
  end

  def birthday
    bd = party_details.
      find_by(name: 'general').
      detail_items.find_by(name: 'birthday').value
    Date.parse(bd)
  end

  def sex
    party_details.find_by(name: 'general').
      detail_items.find_by(name: 'gender').value
  end
end

app/models/section.rb
class Section < ContentItem
  has_many :content_items
end

app/controllers/mml_patients_controller.rb
class MmlPatientsController < ApplicationController
  before_action :set_mml_patient, only: [:show] # :edit, :update, :destroy]

  def index
    @title = 'Patient list'
    @mml_patients = MMLPatient.all
  end

  def show
    @title = "#{@mml_patient.family_name}#{@mml_patient.first_name}"
    @compositions = @mml_patient.ehr.compositions
    respond_to do |format|
      format.html {render html: @mml_patient}
      format.json
      format.xml
      format.any {render :html}
    end
  end

  private
    def set_mml_patient
      @mml_patient = MMLPatient.find(params[:id])
    end

    def mml_patient_params
      params.require(:mml_patient).permit(:master_id)
    end
end

app/helpers/mml_patient_helper.rb
module MmlPatientHelper
end

app/views/mml_patients/_composition.html.erb
<tr>
 <td><%= composition.created_at %></td>
 <td><%= composition.name %></td>
 <td><%= link_to '閲覧', composition %></td>
</tr>

app/views/mml_patients/_mml_patient.html.erb
<tr>
  <td><%= mml_patient.id %></td>
  <td><%= mml_patient.family_name %></td>
  <td><%= mml_patient.first_name %></td>
  <td><%= mml_patient.birthday %></td>
  <td><%= mml_patient.sex %></td>
  <td><%= link_to '閲覧', mml_patient %></td>
</tr>

app/views/mml_patients/index.html.erb
<h1>List - MML Patient Module</h1>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>ID</th>
      <th>姓</th>
      <th>名</th>
      <th>生年月日</th>
      <th>性別</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <%= render @mml_patients %>
  </tbody>
</table>

app/views/mml_patients/show.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-3">
   <h3>Identifiers</h3>
  </div>
  <div class="col-md-3">
    <h3>Profile</h3>
  </div>
  <div class="col-md-6">
    <h3>Contacts</h3>
  </div>
 </div> 
 <div class="row">
  <div class="col-md-3">
    <b>Global ID Issuer:</b>Maiko Network<br />
    <b>Global ID:</b> <%= @mml_patient.master_id %><br />
  <% @mml_patient.other_ids.each do |id| %>
   <b>Issuer:</b> <%= id[:issuer] %><br />
   <b>Local ID:</b> <%= id[:id] %><br />
 <% end %>
  </div>
  <div class="col-md-3">
   <b>氏名:</b> <%= @mml_patient.family_name %> <%= @mml_patient.first_name %><br />
   <b>生年月日:</b> <%= @mml_patient.birthday %><br />
   <b>性別:</b> <%= @mml_patient.sex %><br />
 </div>
 <div class="col-md-3">
 <% @mml_patient.postal_addresses.each do |address| %>
 <address>
 <b>住所種別：</b> <%= address.name %><br />
 <% address.address_details.each do |detail| %><%= detail.value %> <% end %>
<br />
 </address>
 <% end %>
 </div>
 <div class="col-md-3">
 <% @mml_patient.phones.each do |phone| %>
 <b>電話種別:</b> <%= phone.meaning %><br />
 <b>Phone Number:</b> <% phone.address_details.each do |phone| %><%= phone.value %><% end %><br />
 <% end %>
 </div>
 <table class="table table-striped table-bordered">
  <thead>
   <th>作成日時</th>
   <th>文書種別</th>
   <th></th>
  </thead>
  <tbody>
   <%= render partial: "composition", collection: @compositions %>   
  </tbody>
 </table>
</div>
<%= link_to 'MML', mml_patient_path(format: :xml) %> |<%= link_to '戻る', mml_patients_path %>